### ISSUE TITLE
Upgrade rules to use nickel 1.4 features

### ISSUE THREAD

**Issue by smamessier** [nickel-lang/rules_nickel#37]
Is there a work in progress by maintainers of this repository to leverage some of the recent features of nickel such as 
- ability to feed multiple input files to `nickel export`
- use of `NICKEL_IMPORT_PATH`

If not, I and/or @uhlajs would be happy to do it.

**Comment by vkleen** [comment]
There is no work in progress, but that's just due to a lack of time. I'd love any help!

**Comment by uhlajs** [comment]
Both features are utilized in PRs above. I have also extended the examples set. Let me know, what is your opinion.
